# Generated by Django 5.1.2 on 2024-10-27 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MethodeTraitementApp', '0001_initial'),
        ('TraitementApp', '0002_alter_treatment_date_applied'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='methodes_traitement',
            field=models.ManyToManyField(blank=True, related_name='traitements', to='MethodeTraitementApp.methodetraitement'),
        ),
    ]
