# Generated by Django 4.1.13 on 2024-10-26 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeMaladie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, unique=True, verbose_name='Nom de la type de maladie')),
                ('description', models.TextField(verbose_name='Description de la type de maladie')),
                ('image', models.ImageField(blank=True, null=True, upload_to='typemaladies/', verbose_name='Image de la type de maladie')),
                ('is_contagious', models.BooleanField(default=True)),
                ('date_publication', models.DateTimeField(auto_now_add=True, verbose_name='Date de publication')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='typemaladies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'TypeMaladie',
                'verbose_name_plural': 'TypeMaladie',
                'ordering': ['-date_publication'],
            },
        ),
    ]
