# Generated by Django 5.1.2 on 2024-10-27 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maladie', '0002_maladie_types'),
        ('TraitementApp', '0003_treatment_methodes_traitement'),
    ]

    operations = [
        migrations.AddField(
            model_name='maladie',
            name='traitements',
            field=models.ManyToManyField(related_name='maladies', to='TraitementApp.treatment', verbose_name='Traitements'),
        ),
    ]
