# Generated by Django 4.1.13 on 2024-10-29 20:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Maladie', '0003_maladie_traitements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maladie',
            name='owner',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maladies', to=settings.AUTH_USER_MODEL),
        ),
    ]
