# Generated by Django 4.1.13 on 2024-10-29 20:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Maladie', '0004_alter_maladie_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maladie',
            name='owner',
        ),
        migrations.AddField(
            model_name='maladie',
            name='add_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
