# Generated by Django 4.1.13 on 2024-10-25 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ruser',
            options={},
        ),
        migrations.AlterModelManagers(
            name='ruser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='ruser',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='ruser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='ruser',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='ruser',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='ruser',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='ruser',
            name='username',
        ),
        migrations.AddField(
            model_name='ruser',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ruser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='ruser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='ruser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='ruser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ruser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
