# Generated by Django 4.1.13 on 2024-10-26 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0003_ruser_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruser',
            name='role',
            field=models.CharField(default='ADMIN', max_length=50),
        ),
    ]
