# Generated by Django 4.1.13 on 2024-10-26 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('DemandeTraitement', '0002_rendezvous'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandetraitement',
            name='from_farmer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_demandes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='demandetraitement',
            name='to_doc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_demandes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='demandetraitement',
            name='status',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('approuve', 'Approuvé'), ('rejeté', 'Rejeté')], default='en_attente', max_length=20),
        ),
    ]
