# Generated by Django 5.1.2 on 2024-10-26 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DemandeTraitement', '0003_demandetraitement_from_farmer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendezvous',
            name='commentaire',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='demande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DemandeTraitement.demandetraitement'),
        ),
    ]
