# Generated by Django 4.1.13 on 2024-10-27 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DemandeTraitement', '0004_alter_rendezvous_commentaire_and_more'),
        ('DemandeTraitement', '0004_remove_demandetraitement_plant_and_more'),
    ]

    operations = [
    ]
