# Generated by Django 4.1.13 on 2024-10-27 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DemandeTraitement', '0006_remove_demandetraitement_disease'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandetraitement',
            name='title_desease',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
