# Generated by Django 4.1.13 on 2024-10-28 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DemandeTraitement', '0007_demandetraitement_title_desease'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rendezvous',
            name='demande',
        ),
        migrations.AddField(
            model_name='demandetraitement',
            name='rendezv',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DemandeTraitement.rendezvous'),
        ),
    ]
