# Generated by Django 4.1.13 on 2024-10-21 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlantApp', '0002_alter_plant_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diseasedetection',
            name='confidence_score',
            field=models.FloatField(null=True),
        ),
    ]
