# Generated by Django 4.1.13 on 2024-10-27 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DemandeTraitement', '0006_remove_demandetraitement_disease'),
        ('PlantApp', '0003_alter_diseasedetection_confidence_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='diseasedetection',
            name='demande',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DemandeTraitement.demandetraitement'),
        ),
    ]
