# Generated by Django 4.1.13 on 2024-10-28 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PreventionApp', '0001_initial'),
        ('PlantApp', '0004_diseasedetection_demande'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='preventions',
            field=models.ManyToManyField(related_name='plants', to='PreventionApp.prevention', verbose_name='Preventions'),
        ),
    ]
